# Generated by Django 5.0.6 on 2024-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pref',
            name='bot_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pref',
            name='groupchat_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='pref',
            name='pref_string',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
